import type { Locale } from "@/lib/locale";
export const copy = {
  ja: {
    tagline: "Crafting delightful digital experiences.",
    aboutLead: "AI Enablement Engineer",
    aboutBody: [
      "現在は東京を拠点に、企業の生成AI導入とAI駆動開発を支援しています。",
      "元々は、フロントエンド領域に特化したエンジニアとして、UI/UXの改善や開発を行なっていましたが、近年ではAIの発達により、チーム向けにパーソナルナレッジベース/エージェントの仕組み化、人間の認知負荷軽減のための施策をメインの業務として行なっています。",
      "休みの日は、ゲームをしたり、DJを聴いたりプレイしたりして楽しんでいます。",
    ],
    careerLead: "設計から、日々の運用まで。",
    careerIntro:
      "技術で、仕事の進め方やつくり方を少しずつ良くしていきたい。生成AIを軸に、実装から運用まで、現場に寄り添ったものづくりをしています。",
    currentBody:
      "業務への生成AIの導入支援や、AIを活用した開発フローの設計・実装に取り組んでいます。日々の業務が少しでも楽になり、創造的な仕事に集中できる環境づくりを目指しています。",
    pastBody:
      "使いやすく、長く使えるプロダクトを。UI設計から実装・改善まで、フロントエンドを中心に取り組んできました。",
    now: "現在",
    past: "これまで",
    currentRole: "生成AIの導入支援・AI駆動開発",
    pastRole: "フロントエンド開発",
    careerMore: "経歴を詳しく",
    sampleCareer: "期間・案件・実績は後日掲載します。",
    writingLead: "開発日記、日々の学び",
    allArticles: "すべての記事",
    sample: "表示サンプル",
    articleNote:
      "この記事はデザイン確認用のサンプルです。実際の内容は後日掲載します。",
    backWriting: "記事一覧へ",
    backHome: "トップへ",
    read: "記事を読む",
    musicLead: "音楽制作物です。よかったら聞いていってください",
    trackNote: "動作確認用のサンプル音源",
    artNote: "アートワーク・音源は仮素材",
    play: "再生",
    pause: "一時停止",
    seek: "再生位置",
    volume: "音量",
    mute: "ミュート",
    unmute: "ミュート解除",
    audioError: "音源を再生できませんでした。もう一度お試しください。",
    playing: "再生中",
    paused: "一時停止中",
    contactLead: "お気軽に連絡お待ちしております。",
    copyEmail: "メールアドレスをコピー",
    copied: "コピーしました",
    copyFailed:
      "コピーできませんでした。アドレスを選択してコピーしてください。",
    gmail: "Gmailでメールを作成",
    sampleEmail: "メールアドレスは仮表示です。",
    emailPending: "宛先の確定後に利用できます。",
    theme: "テーマ",
    themeLead: "アクセントカラーを選ぶ。",
    color: "カラー",
    colors: {
      default: "デフォルト",
      blue: "ブルー",
      green: "グリーン",
      pink: "ピンク",
    },
    skip: "本文へ移動",
    missing: "ページが見つかりません",
    next: "次の記事",
    contents: "この記事について",
  },
  en: {
    tagline: "Crafting delightful digital experiences.",
    aboutLead: "AI Enablement Engineer",
    aboutBody: [
      "Currently based in Tokyo, I help companies adopt generative AI and move to AI-driven development.",
      "I started out as an engineer specializing in frontend development, building and improving user interfaces and user experiences. As AI has advanced in recent years, my work has shifted toward helping teams establish systems for personal knowledge bases and AI agents, and introducing practices that reduce people's cognitive load.",
      "On my days off, I enjoy gaming, listening to DJ sets, and DJing myself.",
    ],
    careerLead: "From design to everyday operations.",
    careerIntro:
      "Making the way we work and build a little better through technology. With generative AI at the center, I work closely with teams from implementation to everyday operations.",
    currentBody:
      "I help teams adopt generative AI and design and implement AI-assisted development workflows, making daily work easier and creating more room for creative work.",
    pastBody:
      "Building intuitive products that last. My work has centered on frontend engineering, from UI design to implementation and continuous improvement.",
    now: "Now",
    past: "Previously",
    currentRole: "AI adoption & AI-driven development",
    pastRole: "Frontend development",
    careerMore: "Explore my experience",
    sampleCareer: "Dates, projects and experience will be added later.",
    writingLead: "Development notes and everyday learning.",
    allArticles: "All articles",
    sample: "Layout sample",
    articleNote:
      "This is a sample for reviewing the design. The actual article will be added later.",
    backWriting: "Back to blog",
    backHome: "Back home",
    read: "Read article",
    musicLead: "Music I’ve made. Stay a while and have a listen.",
    trackNote: "Sample audio for testing",
    artNote: "Placeholder artwork and audio",
    play: "Play",
    pause: "Pause",
    seek: "Playback position",
    volume: "Volume",
    mute: "Mute",
    unmute: "Unmute",
    audioError: "Unable to play the audio. Please try again.",
    playing: "Playing",
    paused: "Paused",
    contactLead: "Feel free to get in touch.",
    copyEmail: "Copy email address",
    copied: "Copied",
    copyFailed: "Unable to copy. Please select and copy the address.",
    gmail: "Compose in Gmail",
    sampleEmail: "Placeholder email address.",
    emailPending: "Available once the address is confirmed.",
    theme: "Theme",
    themeLead: "Choose an accent color.",
    color: "Color",
    colors: { default: "Default", blue: "Blue", green: "Green", pink: "Pink" },
    skip: "Skip to content",
    missing: "Page not found",
    next: "Next article",
    contents: "About this article",
  },
} satisfies Record<Locale, unknown>;
