import type { Locale } from "@/lib/locale";
export const copy = {
  ja: {
    tagline: "Crafting delightful digital experiences.",
    aboutLead: "AI Enablement Engineer",
    aboutBody: [
      "現在は東京を拠点に、企業の生成AI導入とAI駆動開発を支援しています。",
      "元々は、フロントエンド領域に特化したエンジニアとして、UI/UXの改善や開発を行なっていましたが、近年ではAIの発達により、チーム向けにパーソナルナレッジベース/エージェントの仕組み化、人間の認知負荷軽減のための施策をメインの業務として行なっています。",
    ],
    currentBody:
      "日々、AIの最新情報を取り入れ、業務の生産性向上、プロダクトの可能性を広げる開発に取り組んでいます",
    pastBody:
      "Next.jsを中心にゼロイチでの開発を得意とし、優れたUI/UX、パフォーマンスに優れた開発に取り組んできました",
    now: "現在",
    past: "これまで",
    beforeEngineering: "エンジニア転向前",
    qaRole: "QA・チームリーダー",
    qaBody:
      "大手ゲーム・エンターテインメント企業で、3年間の品質管理業務を経験。そのうち2年間は、リーダー／マネージャーを担当しました。",
    currentRole: "AI Enablement Engineer（生成AI導入支援・AI駆動開発推進）",
    pastRole: "フロントエンド開発",
    careerMore: "経歴を詳しく",
    sampleCareer: "期間・案件・実績は後日掲載します。",
    writingLead: "開発日記、日々の学び",
    allArticles: "すべての記事",
    sample: "表示サンプル",
    articleNote:
      "この記事はデザイン確認用のサンプルです。実際の内容は後日掲載します。",
    backWriting: "記事一覧へ",
    backHome: "トップへ",
    read: "記事を読む",
    musicLead:
      "AIを使って制作した楽曲の紹介です。よかったら聴いていってください",
    trackList: "トラックリスト",
    seasonalSpecial: "季節限定スペシャル",
    selectTrack: "選択して再生",
    play: "再生",
    pause: "一時停止",
    seek: "再生位置",
    volume: "音量",
    mute: "ミュート",
    unmute: "ミュート解除",
    audioError: "音源を再生できませんでした。もう一度お試しください。",
    playing: "再生中",
    paused: "一時停止中",
    contactLead: "お気軽にご連絡ください",
    copyEmail: "メールアドレスをコピー",
    copied: "コピーしました",
    copyFailed:
      "コピーできませんでした。アドレスを選択してコピーしてください。",
    gmail: "Gmailでメールを作成",
    sampleEmail: "メールアドレスは仮表示です。",
    emailPending: "宛先の確定後に利用できます。",
    theme: "テーマ",
    themeLead: "アクセントカラーを選ぶ。",
    color: "カラー",
    colors: {
      default: "デフォルト",
      blue: "ブルー",
      green: "グリーン",
      pink: "ピンク",
    },
    skip: "本文へ移動",
    missing: "ページが見つかりません",
    next: "次の記事",
    contents: "この記事について",
  },
  en: {
    tagline: "Crafting delightful digital experiences.",
    aboutLead: "AI Enablement Engineer",
    aboutBody: [
      "Currently based in Tokyo, I help companies adopt generative AI and move to AI-driven development.",
      "I started out as an engineer specializing in frontend development, building and improving user interfaces and user experiences. As AI has advanced in recent years, my work has shifted toward helping teams establish systems for personal knowledge bases and AI agents, and introducing practices that reduce people's cognitive load.",
    ],
    currentBody:
      "I keep up with the latest developments in AI and apply them to improve productivity and expand what products can do.",
    pastBody:
      "I specialize in building products from the ground up with Next.js, focusing on excellent UI/UX and high performance.",
    now: "Now",
    past: "Previously",
    beforeEngineering: "Before engineering",
    qaRole: "QA / Team Leader",
    qaBody:
      "Spent three years in quality control at a major gaming and entertainment company, including two years as a team leader / manager.",
    currentRole:
      "AI Enablement Engineer (Generative AI adoption & AI-driven development)",
    pastRole: "Frontend development",
    careerMore: "Explore my experience",
    sampleCareer: "Dates, projects and experience will be added later.",
    writingLead: "Development notes and everyday learning.",
    allArticles: "All articles",
    sample: "Layout sample",
    articleNote:
      "This is a sample for reviewing the design. The actual article will be added later.",
    backWriting: "Back to blog",
    backHome: "Back home",
    read: "Read article",
    musicLead: "Music I’ve made. Stay a while and have a listen.",
    trackList: "Track list",
    seasonalSpecial: "Seasonal special",
    selectTrack: "Select and play",
    play: "Play",
    pause: "Pause",
    seek: "Playback position",
    volume: "Volume",
    mute: "Mute",
    unmute: "Unmute",
    audioError: "Unable to play the audio. Please try again.",
    playing: "Playing",
    paused: "Paused",
    contactLead: "Feel free to get in touch.",
    copyEmail: "Copy email address",
    copied: "Copied",
    copyFailed: "Unable to copy. Please select and copy the address.",
    gmail: "Compose in Gmail",
    sampleEmail: "Placeholder email address.",
    emailPending: "Available once the address is confirmed.",
    theme: "Theme",
    themeLead: "Choose an accent color.",
    color: "Color",
    colors: { default: "Default", blue: "Blue", green: "Green", pink: "Pink" },
    skip: "Skip to content",
    missing: "Page not found",
    next: "Next article",
    contents: "About this article",
  },
} satisfies Record<Locale, unknown>;
